In [1]:
!pip install nltk spacy scikit-learn pandas numpy matplotlib seaborn transformers sentence-transformers

!python -m spacy download en_core_web_sm

  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)

  Attempting uninstall: numpy

    Found existing installation: numpy 1.26.4

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
    Uninstalling numpy-1.26.4:
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   --------------------------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 3.6.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.2.0 which is incompatible.
ibm-watson-machine-learning 1.0.368 requires pandas<2.2.0,>=0.24.2, but you have pandas 2.3.3 which is incompatible.
llama-index-readers-file 0.5.4 requires pandas<2.3.0, but you have pandas 2.3.3 which is incompatible.
ultralytics 8.3.88 requires numpy<=2.1.1,>=1.23.0, but you have numpy 2.2.6 which is incompatible.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ------------------ --------------------- 6.0/12.8 MB 30.7 MB/s eta 0:00:01
     --------------------------------- ----- 11.0/12.8 MB 28.7 MB/s eta 0:00:01
     --------------------------------------- 12.8/12.8 MB 21.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')



[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import nltk
import spacy
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sentence_transformers import SentenceTransformer

c:\Users\vnina\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vnina\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vnina\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [8]:
text = "NLP is amazing. Machines can understand human language!"

In [10]:
from nltk.tokenize import word_tokenize

nltk.download('punkt_tab', quiet=True)
tokens = word_tokenize(text)

print(tokens)

['NLP', 'is', 'amazing', '.', 'Machines', 'can', 'understand', 'human', 'language', '!']


In [11]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

filtered = [word for word in tokens if word.lower() not in stop_words]

print(filtered)

['NLP', 'amazing', '.', 'Machines', 'understand', 'human', 'language', '!']


In [12]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

stemmed = [stemmer.stem(word) for word in filtered]

print(stemmed)

['nlp', 'amaz', '.', 'machin', 'understand', 'human', 'languag', '!']


In [13]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("The cats are running in the garden")

lemmas = [token.lemma_ for token in doc]

print(lemmas)

['the', 'cat', 'be', 'run', 'in', 'the', 'garden']


In [14]:
sentences = [
    "I love NLP",
    "NLP is amazing",
    "I love machine learning"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(sentences)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['amazing' 'is' 'learning' 'love' 'machine' 'nlp']
[[0 0 0 1 0 1]
 [1 1 0 0 0 1]
 [0 0 1 1 1 0]]


In [15]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(sentences)

print(X.toarray())

[[0.         0.         0.         0.70710678 0.         0.70710678]
 [0.62276601 0.62276601 0.         0.         0.         0.4736296 ]
 [0.         0.         0.62276601 0.4736296  0.62276601 0.        ]]


In [16]:
data = {
    "text": [
        "I love this product",
        "This is amazing",
        "I hate this",
        "Very bad experience",
        "I really like it",
        "Worst thing ever"
    ],
    "label": [1,1,0,0,1,0]
}

df = pd.DataFrame(data)

In [17]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["text"])
y = df["label"]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [20]:
preds = model.predict(X_test)

print(preds)

[0 0]


In [21]:
accuracy = accuracy_score(y_test, preds)

print("Accuracy:", accuracy)

Accuracy: 0.0


In [22]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [23]:
sentences = [
    "I love NLP",
    "Artificial Intelligence is powerful",
    "I enjoy machine learning"
]

embeddings = model.encode(sentences)

print(embeddings.shape)

(3, 384)
